Make test dependency clearer
heremaps/map-linkbuilder-app pull request #12
Opened 2017-05-23 15:29 UTC by freethan

README clarifications re selenium-webdriver and Node minimum version

2017-05-23 15:31 UTC, sschuberth commented on README.md
> +`npm run test`
Just `npm test`?

2017-05-23 15:44 UTC, freethan commented on README.md
> +`npm run test`
Sure, no problem. It's one of the default targets.

2017-05-24 07:12 UTC, sschuberth requested changes

2017-05-24 07:12 UTC, sschuberth commented on README.md
> +Make sure you have already installed the latest version of `Node` (at least version 6.10.3) and `NPM` (Node Package Manager) and then run:
Strictly speaking, I would not use `code` formatting here, as you're referring to the literal name of the apps, not to the name of the command line executables. So, IMO, either use Node and NPM, or `node` and `npm` (lower case).

2017-05-24 07:12 UTC, sschuberth commented on README.md
> +`npm install`
I don't really see a reason for this change as from a visual appearance perspective they look the same in the end: `backticks` should be used for inline code, and

    four spaces indentation

for code blocks.

2017-05-24 10:33 UTC, sschuberth approved these changes

2017-05-24 15:11 UTC, merged